permalink: /:day-:month-:year/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "Blog do Bruno Viecelli"
email: "bviecelli@gmail.com"
description: "Engenheiro de Computação"
github_username:  "bviecelli"
swiftype_searchId: ""
disqus_shortname: "brunoviecelli"




url: "http://bviecelli.eng.br"
imgrepo: "http://bviecelli.eng.br/static/img"

